#Help function
def help(arg):
	if not arg:
		print("")
		print("Quick list of available commands.")
		print("For more info type help [command].")
		print("")
		print("Commands:")
		print("")
		print("  help    Displays this quick help information or help on specified available command.")
		print("  graph   Displays current status on specified country.")
		print("  update  Updates database.")
		print("  bar     Displays specified cases on a daily, weekly or monthly period for the given country.")
		print("")
	elif arg == 'bar':
		print("")
		print("BAR:     Displays specified cases on a daily, weekly or monthly period for the given country.")
		print("")
		print("Usage:   bar [country] [case] [grouping] [period]")
		print("Default: bar global confirmed daily 1.1:31.12")
		print("")
		print("Options:")
		print("  [country]   country name, iso2, iso3 or code of the country")
		print("  [case]      confirmed, deaths or recovered. 'c', 'd' or 'r' as shortcuts")
		print("  [grouping]  daily, weekly or monthly stats. 'd', 'w' or 'm' as shortcuts")
		print("  [period]    format is from_date:to_date")
		print("")
		print("Period format:")
		print("  [day.month:day.month] if daily grouping (ex. 30.3:4.4 means 30th March to 4th April inclusive)")
		print("  [week:week]           if weekly grouping (ex. 12:15 means ISO week 12 to week 15 inclusive)")
		print("  [month:month]         if monthly grouping (ex. 2:5 means months February to May inclusive)")
		print("  If period is ommited it is replaced with full period for the year (daily - 1.1:31.12, weekly - 0:53, monthly 1:12)")
		print("  If one side in period is ommited it is replaced with begining or the end of the year:")
		print("  - [from_date:] from given day (week, month) to the end of the year")
		print("  - [:to_date]   from begining of the year to given day (week, month)")
		print("")
		print("Examples:")
		print("  bar italy recovered weekly 9:14 --- Weekly recovered cases in Italy between weeks 9 to 14")
		print("  bar global c m :5               --- Monthly confirmed cases worldwide from begining of the year to May")
		print("  bar china c daily 1.3:15.3      --- Daily confirmed cases in China from 1st to 15th March")
		print("")
	else:
		raise ValueError(f"*** {arg}: Unknown command.")

